apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bundle-cache
  labels:
    app: web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-modules-cache
  labels:
    app: web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: precompile-cache
  labels:
    app: web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: svc-for-rails
  labels:
    app: web-app
  annotations:
    node-type: NodePort
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 8080
      protocol: TCP
  selector:
    app: web-app

---
apiVersion: v1
kind: Service
metadata:
  name: svc-for-rails
  labels:
    app: web-app
  annotations:
    node-type: LoadBalancer
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 8080
  selector:
    app: web-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      volumes:
        - name: bundle-persistent-storage
          persistentVolumeClaim:
            claimName: bundle-cache
        - name: node-modules-persistent-storage
          persistentVolumeClaim:
            claimName: node-modules-cache
        - name: precompile-persistent-storage
          persistentVolumeClaim:
            claimName: precompile-cache
        - name: public-app
          emptyDir: {}
        - name: tmp-app
          emptyDir: {}

      containers:
      - name: reverse-proxy
        volumeMounts:
          - name: tmp-app
            mountPath: /app/tmp
          - name: public-app
            mountPath: /app/public

        ports:
          - containerPort: 80
            name: "reverse-proxy"
        image: "localhost:5000/airnguru/nginx:latest"
      - name: rails-app
        volumeMounts:
          - name: bundle-persistent-storage
            mountPath: /app/vendor/gems
          - name: node-modules-persistent-storage
            mountPath: /app/node_modules
          - name: precompile-persistent-storage
            mountPath: /app/tmp/cache
          - name: tmp-app
            mountPath: /app/tmp
          - name: public-app
            mountPath: /app/public
        image: "localhost:5000/airnguru/rails:latest"
        env:
          - name: RAILS_MASTER_KEY
            value: "a55eb4bc75a5d34ddf92c2c6eb7ba19a"

        command: ["bundle", "exec", "puma", "-C", "config/puma/production.rb"]
