apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      volumes:
        - name: bundle-installation
          emptyDir: {}
    emptyDir: {}
      containers:
      - name: reverse-proxy
        ports:
          - containerPort: 80
            name: "reverse-proxy"
        image: "localhost:5000/airnguru/nginx:latest"
      - name: rails-app
        volumeMounts:
          - name: shared-data
            mountPath: /usr/share/nginx/html
        image: "localhost:5000/airnguru/rails:latest"
        command: ["bundle", "exec", "puma", "-C", "config/puma/production.rb"]
